package util

var AIRLINES = map[string]string{
	"AA":  "American Airlines",
	"AF":  "Air France",
	"BA":  "British Airways",
	"CX":  "Cathay Pacific",
	"DL":  "Delta Air Lines",
	"EK":  "Emirates",
	"JL":  "Japan Airlines",
	"LH":  "Lufthansa",
	"NH":  "All Nippon Airways (ANA)",
	"PR":  "Philippine Airlines",
	"QF":  "Qantas",
	"QR":  "Qatar Airways",
	"SQ":  "Singapore Airlines",
	"UA":  "United Airlines",
	"TK":  "Turkish Airlines",
	"VS":  "Virgin Atlantic",
	"AC":  "Air Canada",
	"AI":  "Air India",
	"AZ":  "Alitalia",
	"AY":  "Finnair",
	"CA":  "Air China",
	"CI":  "China Airlines",
	"CZ":  "China Southern Airlines",
	"ET":  "Ethiopian Airlines",
	"EY":  "Etihad Airways",
	"GA":  "Garuda Indonesia",
	"IB":  "Iberia",
	"KE":  "Korean Air",
	"KLM": "KLM Royal Dutch Airlines",
	"LY":  "El Al Israel Airlines",
	"MH":  "Malaysia Airlines",
	"OS":  "Austrian Airlines",
	"SA":  "South African Airways",
	"SK":  "SAS Scandinavian Airlines",
	"SU":  "Aeroflot Russian Airlines",
	"TG":  "Thai Airways",
	"VN":  "Vietnam Airlines",
	"WN":  "Southwest Airlines",
	"ZB":  "Monarch Airlines",
}

var AIRPORTS = map[string]struct {
	Name    string
	City    string
	Country string
	TZ      string
}{
	"ATL": {Name: "Hartsfield–Jackson Atlanta International Airport", City: "Atlanta", Country: "United States", TZ: "America/New_York"},
	"PEK": {Name: "Beijing Capital International Airport", City: "Beijing", Country: "China", TZ: "Asia/Shanghai"},
	"LHR": {Name: "London Heathrow Airport", City: "London", Country: "United Kingdom", TZ: "Europe/London"},
	"ORD": {Name: "O'Hare International Airport", City: "Chicago", Country: "United States", TZ: "America/Chicago"},
	"LAX": {Name: "Los Angeles International Airport", City: "Los Angeles", Country: "United States", TZ: "America/Los_Angeles"},
	"DXB": {Name: "Dubai International Airport", City: "Dubai", Country: "United Arab Emirates", TZ: "Asia/Dubai"},
	"HND": {Name: "Tokyo Haneda Airport", City: "Tokyo", Country: "Japan", TZ: "Asia/Tokyo"},
	"CDG": {Name: "Charles de Gaulle Airport", City: "Paris", Country: "France", TZ: "Europe/Paris"},
	"DFW": {Name: "Dallas/Fort Worth International Airport", City: "Dallas", Country: "United States", TZ: "America/Chicago"},
	"AMS": {Name: "Amsterdam Schiphol Airport", City: "Amsterdam", Country: "Netherlands", TZ: "Europe/Amsterdam"},
	"FRA": {Name: "Frankfurt Airport", City: "Frankfurt", Country: "Germany", TZ: "Europe/Berlin"},
	"IST": {Name: "Istanbul Airport", City: "Istanbul", Country: "Turkey", TZ: "Europe/Istanbul"},
	"SIN": {Name: "Singapore Changi Airport", City: "Singapore", Country: "Singapore", TZ: "Asia/Singapore"},
	"ICN": {Name: "Incheon International Airport", City: "Seoul", Country: "South Korea", TZ: "Asia/Seoul"},
	"JFK": {Name: "John F. Kennedy International Airport", City: "New York", Country: "United States", TZ: "America/New_York"},
	"MEX": {Name: "Mexico City International Airport", City: "Mexico City", Country: "Mexico", TZ: "America/Mexico_City"},
	"GRU": {Name: "São Paulo-Guarulhos International Airport", City: "São Paulo", Country: "Brazil", TZ: "America/Sao_Paulo"},
	"SYD": {Name: "Sydney Kingsford Smith Airport", City: "Sydney", Country: "Australia", TZ: "Australia/Sydney"},
	"YYZ": {Name: "Toronto Pearson International Airport", City: "Toronto", Country: "Canada", TZ: "America/Toronto"},
	"BKK": {Name: "Suvarnabhumi Airport", City: "Bangkok", Country: "Thailand", TZ: "Asia/Bangkok"},
	"JNB": {Name: "O. R. Tambo International Airport", City: "Johannesburg", Country: "South Africa", TZ: "Africa/Johannesburg"},
	"DEL": {Name: "Indira Gandhi International Airport", City: "Delhi", Country: "India", TZ: "Asia/Kolkata"},
	"SFO": {Name: "San Francisco International Airport", City: "San Francisco", Country: "United States", TZ: "America/Los_Angeles"},
	"MAD": {Name: "Adolfo Suárez Madrid–Barajas Airport", City: "Madrid", Country: "Spain", TZ: "Europe/Madrid"},
	"MUC": {Name: "Munich Airport", City: "Munich", Country: "Germany", TZ: "Europe/Berlin"},
	"MIA": {Name: "Miami International Airport", City: "Miami", Country: "United States", TZ: "America/New_York"},
	"BCN": {Name: "Barcelona–El Prat Airport", City: "Barcelona", Country: "Spain", TZ: "Europe/Madrid"},
	"FCO": {Name: "Leonardo da Vinci–Fiumicino Airport", City: "Rome", Country: "Italy", TZ: "Europe/Rome"},
	"LGA": {Name: "LaGuardia Airport", City: "New York", Country: "United States", TZ: "America/New_York"},
	"SEA": {Name: "Seattle–Tacoma International Airport", City: "Seattle", Country: "United States", TZ: "America/Los_Angeles"},
	"LAS": {Name: "McCarran International Airport", City: "Las Vegas", Country: "United States", TZ: "America/Los_Angeles"},
	"PHX": {Name: "Phoenix Sky Harbor International Airport", City: "Phoenix", Country: "United States", TZ: "America/Phoenix"},
	"BOS": {Name: "Logan International Airport", City: "Boston", Country: "United States", TZ: "America/New_York"},
	"HKG": {Name: "Hong Kong International Airport", City: "Hong Kong", Country: "Hong Kong SAR", TZ: "Asia/Hong_Kong"},
	"MCO": {Name: "Orlando International Airport", City: "Orlando", Country: "United States", TZ: "America/New_York"},
	"IAD": {Name: "Washington Dulles International Airport", City: "Washington, D.C.", Country: "United States", TZ: "America/New_York"},
	"DEN": {Name: "Denver International Airport", City: "Denver", Country: "United States", TZ: "America/Denver"},
	"YVR": {Name: "Vancouver International Airport", City: "Vancouver", Country: "Canada", TZ: "America/Vancouver"},
	"BOM": {Name: "Chhatrapati Shivaji Maharaj International Airport", City: "Mumbai", Country: "India", TZ: "Asia/Kolkata"},
	"SVO": {Name: "Sheremetyevo International Airport", City: "Moscow", Country: "Russia", TZ: "Europe/Moscow"},
	"ZRH": {Name: "Zurich Airport", City: "Zurich", Country: "Switzerland", TZ: "Europe/Zurich"},
	"VIE": {Name: "Vienna International Airport", City: "Vienna", Country: "Austria", TZ: "Europe/Vienna"},
	"CPT": {Name: "Cape Town International Airport", City: "Cape Town", Country: "South Africa", TZ: "Africa/Johannesburg"},
	"KUL": {Name: "Kuala Lumpur International Airport", City: "Kuala Lumpur", Country: "Malaysia", TZ: "Asia/Kuala_Lumpur"},
	"BNE": {Name: "Brisbane Airport", City: "Brisbane", Country: "Australia", TZ: "Australia/Brisbane"},
	"LIM": {Name: "Jorge Chávez International Airport", City: "Lima", Country: "Peru", TZ: "America/Lima"},
	"GIG": {Name: "Rio de Janeiro–Galeão International Airport", City: "Rio de Janeiro", Country: "Brazil", TZ: "America/Sao_Paulo"},
	"MNL": {Name: "Ninoy Aquino International Airport", City: "Manila", Country: "Philippines", TZ: "Asia/Manila"},
	"CGK": {Name: "Soekarno-Hatta International Airport", City: "Jakarta", Country: "Indonesia", TZ: "Asia/Jakarta"},
	"DPS": {Name: "Ngurah Rai International Airport", City: "Denpasar", Country: "Indonesia", TZ: "Asia/Makassar"},
	"SUB": {Name: "Juanda International Airport", City: "Surabaya", Country: "Indonesia", TZ: "Asia/Jakarta"},
	"UPG": {Name: "Sultan Hasanuddin International Airport", City: "Makassar", Country: "Indonesia", TZ: "Asia/Makassar"},
	"YIA": {Name: "Yogyakarta International Airport", City: "Yogyakarta", Country: "Indonesia", TZ: "Asia/Jakarta"},
}
